'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Save, ThumbsUp, ThumbsDown, Loader2 } from 'lucide-react'
import { useCreateNote } from '@/lib/hooks/use-notes'
import { toast } from 'sonner'
import { useI18n } from '@/lib/i18n'

interface MessageActionsProps {
  content: string
  notebookId?: string
  messageId?: string
}

export function MessageActions({ content, notebookId, messageId }: MessageActionsProps) {
  const [feedback, setFeedback] = useState<'up' | 'down' | null>(null)
  const createNote = useCreateNote()
  const { t } = useI18n()

  const sendFeedback = async (rating: 'up' | 'down' | null) => {
    if (!messageId || !/^\d+$/.test(messageId)) {
      toast.error(t('chat.feedbackUnavailable'))
      return
    }

    try {
      const response = await fetch(`/api/chat/messages/${messageId}/feedback`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ rating }),
      })

      if (!response.ok) {
        const errorText = await response.text()
        throw new Error(errorText || `HTTP ${response.status}`)
      }
    } catch (error) {
      console.error('Failed to send feedback:', error)
      toast.error(t('chat.feedbackFailed'))
      setFeedback((prev) => (prev === rating ? null : prev))
    }
  }

  const handleSaveToNote = () => {
    if (!notebookId) {
      toast.error(t('chat.saveNoteMissing'))
      return
    }

    createNote.mutate({
      content,
      note_type: 'ai',
      notebook_id: notebookId,
      // Title will be auto-generated by the API for AI notes
    })
  }

  const handleFeedback = (next: 'up' | 'down') => {
    const nextValue = feedback === next ? null : next
    setFeedback(nextValue)
    void sendFeedback(nextValue)
  }

  return (
    <TooltipProvider>
      <div className="flex gap-1">
        {notebookId && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="h-7 px-2"
                onClick={handleSaveToNote}
                disabled={createNote.isPending}
              >
                {createNote.isPending ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Save className="h-3.5 w-3.5" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              <p>{t('action.saveToNotes')}</p>
            </TooltipContent>
          </Tooltip>
        )}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className={`h-7 px-2 ${feedback === 'up' ? 'text-emerald-600' : ''}`}
              onClick={() => handleFeedback('up')}
              disabled={createNote.isPending}
            >
              <ThumbsUp className="h-3.5 w-3.5" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>{t('action.goodAnswer')}</p>
          </TooltipContent>
        </Tooltip>
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className={`h-7 px-2 ${feedback === 'down' ? 'text-rose-600' : ''}`}
              onClick={() => handleFeedback('down')}
              disabled={createNote.isPending}
            >
              <ThumbsDown className="h-3.5 w-3.5" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>{t('action.badAnswer')}</p>
          </TooltipContent>
        </Tooltip>
      </div>
    </TooltipProvider>
  )
}
